# Generated by Django 5.2.1 on 2026-04-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='unit_price',
        ),
    ]
