# Generated by Django 5.2.1 on 2026-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderline_line_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
