services:

  # ─── Catalog Service ───────────────────────────────────────────────────────
  catalog_db:
    image: postgres:15-alpine
    container_name: catalog_db
    restart: always
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalog_user -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  catalog_web:
    build: ./catalog-service
    container_name: catalog_service
    hostname: catalog-web
    restart: always
    ports:
      - "8001:8001"
    environment:
      DATABASE_NAME: catalog_db
      DATABASE_USER: catalog_user
      DATABASE_PASSWORD: catalog_pass
      DATABASE_HOST: catalog_db
      DATABASE_PORT: 5432
    depends_on:
      catalog_db:
        condition: service_healthy

  # ─── Customers Service ─────────────────────────────────────────────────────
  customers_db:
    image: postgres:15-alpine
    container_name: customers_db
    restart: always
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_password
    volumes:
      - customers_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U customer_user -d customer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  customers_web:
    build: ./customers-sercice
    container_name: customers_service
    hostname: customers-web
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: customer_user
      POSTGRES_PASSWORD: customer_password
      DB_HOST: customers_db
      DB_PORT: 5432
      DJANGO_SECRET_KEY: change_me_in_dev
      DJANGO_DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1,customers-web"
    depends_on:
      customers_db:
        condition: service_healthy

  # ─── Orders Service ────────────────────────────────────────────────────────
  orders_db:
    image: postgres:16-alpine
    container_name: orders_db
    restart: always
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    volumes:
      - orders_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  orders_web:
    build: ./orders-service
    container_name: orders_service
    hostname: orders-web
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      DB_HOST: orders_db
      DB_PORT: 5432
      DJANGO_SECRET_KEY: order_secret_key_123
      DJANGO_DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1,orders-web"
      CATALOG_SERVICE_URL: http://catalog-web:8001
    depends_on:
      orders_db:
        condition: service_healthy

  # ─── Frontend ────────────────────────────────────────────────────────
  frontend:
    build: ./frontend
    container_name: zalandouille_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_CUSTOMER_URL: http://customers-web:8000
      VITE_ORDER_URL: http://orders-web:8002
      VITE_CATALOG_URL: http://catalog-web:8001

    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - customers_web
      - catalog_web
      - orders_web


volumes:
  catalog_postgres_data:
  customers_postgres_data:
  orders_postgres_data:
