-- Seed data Mini Zalando - category
-- Rows: 50

INSERT INTO catalog_category (id, name, slug) VALUES
(1, 'Lingerie fine', 'lingerie-fine'),
(2, 'Sneakers femme', 'sneakers-femme'),
(3, 'Sneakers homme', 'sneakers-homme'),
(4, 'Escarpins', 'escarpins'),
(5, 'Bottes et bottines', 'bottes-et-bottines'),
(6, 'Sandales', 'sandales'),
(7, 'Manteaux femme', 'manteaux-femme'),
(8, 'Manteaux homme', 'manteaux-homme'),
(9, 'Vestes en cuir', 'vestes-en-cuir'),
(10, 'Doudounes', 'doudounes'),
(11, 'Robes de soirée', 'robes-de-soiree'),
(12, 'Robes casual', 'robes-casual'),
(13, 'Jupes', 'jupes'),
(14, 'Jeans femme', 'jeans-femme'),
(15, 'Jeans homme', 'jeans-homme'),
(16, 'Pantalons chino', 'pantalons-chino'),
(17, 'Pantalons cargo', 'pantalons-cargo'),
(18, 'T-shirts femme', 't-shirts-femme'),
(19, 'T-shirts homme', 't-shirts-homme'),
(20, 'Chemises', 'chemises'),
(21, 'Pulls et cardigans', 'pulls-et-cardigans'),
(22, 'Sweats hoodies', 'sweats-hoodies'),
(23, 'Blazers', 'blazers'),
(24, 'Costumes', 'costumes'),
(25, 'Sacs à main', 'sacs-a-main'),
(26, 'Sacs de sport', 'sacs-de-sport'),
(27, 'Sacs à dos', 'sacs-a-dos'),
(28, 'Ceintures', 'ceintures'),
(29, 'Lunettes de soleil', 'lunettes-de-soleil'),
(30, 'Bijoux fantaisie', 'bijoux-fantaisie'),
(31, 'Montres', 'montres'),
(32, 'Écharpes et foulards', 'echarpes-et-foulards'),
(33, 'Bonnets et casquettes', 'bonnets-et-casquettes'),
(34, 'Maillots de bain femme', 'maillots-de-bain-femme'),
(35, 'Maillots de bain homme', 'maillots-de-bain-homme'),
(36, 'Sportswear femme', 'sportswear-femme'),
(37, 'Sportswear homme', 'sportswear-homme'),
(38, 'Running', 'running'),
(39, 'Yoga et pilates', 'yoga-et-pilates'),
(40, 'Outdoor randonnée', 'outdoor-randonnee'),
(41, 'Sous-vêtements femme', 'sous-vetements-femme'),
(42, 'Sous-vêtements homme', 'sous-vetements-homme'),
(43, 'Pyjamas femme', 'pyjamas-femme'),
(44, 'Pyjamas homme', 'pyjamas-homme'),
(45, 'Enfant fille', 'enfant-fille'),
(46, 'Enfant garçon', 'enfant-garcon'),
(47, 'Bébé', 'bebe'),
(48, 'Beauté parfum', 'beaute-parfum'),
(49, 'Accessoires cheveux', 'accessoires-cheveux'),
(50, 'Chaussettes', 'chaussettes');


